{{- if .Values.nsp.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "docker-2-helm.fullname" . }}-nsp
  namespace: java-hello-world
spec:
  podSelector: {}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
  - Ingress
  - Egress
{{ end }}
