{{- if .Values.nsp.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "java-app.fullname" . }}-nsp
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
  - Ingress
  - Egress
{{ end }}
